Automated e2e tests
redbadger/count-dracula pull request #27
Opened 2021-04-07 11:09 UTC by DimplePatel

2021-04-08 15:38 UTC, anubha22 approved these changes

2021-04-08 16:54 UTC, pataruco requested changes

2021-04-08 16:54 UTC, pataruco commented on web/e2e/index.ts
> +import puppeteer from 'puppeteer';
@DimplePatel I cannot see any test assertions here, like

```js
expect(something).toBe(true)
```

2021-04-10 16:46 UTC, pataruco approved these changes
Well done!

2021-04-10 16:47 UTC, merged